[package]
name = "AoC2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day01-1"
path = "src/day01/bin/part1.rs"

[[bin]]
name = "day01-2"
path = "src/day01/bin/part2.rs"

[dependencies]
